/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 13.07.2026 19:27:43

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 3168;
#else
constexpr int kTensorArenaSize = 2144;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,637 } };
const TfArray<1, float> quant0_scale = { 1, { 0.050236541777849197, } };
const TfArray<1, int> quant0_zero = { 1, { 23 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 49, 13, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 49, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 25, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 25, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data5[2] = { -1, 208, };
const TfArray<1, int> tensor_dimension5 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data6[8] = { 205, 606, 957, -1147, 39, -539, -202, -18, };
const TfArray<1, int> tensor_dimension6 = { 1, { 8 } };
const TfArray<1, float> quant6_scale = { 1, { 0.00063008884899318218, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[8*208] = { 
  12, -6, 3, -15, 7, -44, -1, 23, 3, 15, 5, 5, -33, 37, -6, 4, 3, -55, -18, -78, 10, -26, -2, 1, 4, 6, 15, -58, -36, 14, -23, -4, -2, -21, -15, -17, 7, -15, -9, -1, -22, -2, 7, -1, -54, 8, -31, 16, -18, 10, 1, 1, 17, -2, 14, -6, 3, -12, 5, 2, -46, 8, -23, 8, -19, 18, 7, 11, 29, 8, 10, -35, 20, 3, 11, 28, -36, 5, -39, 3, -33, 20, 5, 14, 1, 7, 9, -24, 29, 20, 4, 24, -42, -12, -21, -1, -49, 18, 3, 22, 24, 0, 4, -35, 23, 17, 15, -13, -30, -4, -30, 3, -66, 19, -1, 16, 7, -15, 7, -35, 18, 23, 13, -25, -25, 5, -18, -1, -63, 17, 16, 16, -19, -22, 16, -23, 21, 22, 14, -17, -26, 5, -11, 8, -49, 9, 6, 5, -3, -32, 8, 7, 20, 24, 16, -25, -13, 6, -5, 12, -34, 0, 9, 15, 16, -26, 3, 4, 4, 19, 3, -36, -18, 1, -1, 5, -3, 12, 3, 23, 19, -21, 14, 1, 18, -18, 20, -30, -8, 11, 3, 7, -17, -21, -33, 2, 15, -13, 9, 0, -19, -32, 9, -7, -17, 15, 34, 25, 
  5, -29, 9, -26, 10, 14, -26, 12, -36, -26, 25, 4, -27, 34, -6, -3, -5, -20, -7, -29, 8, -9, 3, 1, -4, -6, 16, -13, -10, 12, -5, 11, 9, -48, -29, -2, 14, -26, 4, -1, -25, -3, 13, 0, -25, 7, -15, 4, -13, -58, -35, -6, 13, -6, 7, -1, -13, 4, 13, 4, -21, 13, -20, 8, -38, -66, -57, 15, 12, 9, 0, -13, -19, 22, 15, -16, 7, 4, -25, 17, -8, -26, -36, 17, 10, 1, -1, -61, -13, 17, 7, -1, 13, 5, -4, 12, 19, -41, -25, 4, 21, -19, 10, -34, -12, 17, -12, 5, -13, -23, -6, 15, 14, -38, -66, -21, 24, -8, 11, -4, -5, 11, -14, 18, -31, -7, -1, 22, 18, -15, -36, -5, 30, -6, 0, -46, -7, 20, 13, 20, -12, -30, 11, -37, 7, -2, -3, -13, 8, -1, -24, 5, -32, 9, -12, 19, -8, -30, 13, 2, 13, -11, -7, -24, 6, -16, -7, 2, -24, 22, -16, 0, 1, -21, 14, 19, 3, -5, -10, -55, 10, -16, -22, 4, -28, 0, -6, 3, 2, 8, 14, -4, 11, -25, 34, -16, 9, -14, -26, 7, -29, -10, -27, 16, 5, -1, -2, -2, 
  9, -10, -4, -13, 12, -11, -5, 17, -13, -16, 7, -12, -3, 12, -16, -14, 19, -42, -18, -19, 8, 5, 6, -4, -12, -6, 13, -15, -7, 13, -28, -10, -18, -13, -11, -36, 9, 11, -25, -1, -19, -8, 15, -30, -6, 8, -14, -19, -17, -20, 0, -16, 15, 15, -39, 3, -17, -13, 13, -6, -37, 15, -20, -19, -6, -8, -3, -8, 7, 27, -65, 3, -34, -31, 11, -15, -10, 10, -1, -19, 4, -12, 11, -19, -3, 25, -78, 2, -31, -44, 16, -5, -9, 16, -6, -35, 9, -7, 19, -46, -8, 23, -56, 6, -50, -35, 11, -6, 2, 9, 5, -13, -1, -21, 14, -39, 21, 6, -50, 13, -40, -41, -4, -8, -5, 9, 3, -37, 13, -26, 19, 0, 25, -3, -26, 0, -56, -71, -13, 0, -2, 16, 0, -34, 13, -31, 4, -3, 18, 16, -15, 2, -42, -35, -17, 2, 5, 4, 0, -21, 16, -26, 2, -13, 25, -1, -5, 25, -49, -22, -25, 8, 10, 20, 1, 3, 7, -28, -4, -7, 21, -30, 1, 12, -36, -35, -45, 2, 9, 28, 6, -26, -5, -28, 16, 10, 22, -24, 23, -3, 2, -7, -48, -5, 4, -14, 4, -12, 
  0, 3, -3, 17, -34, -8, 2, 0, 14, 18, 10, 2, -3, -26, -6, 9, -13, 15, 9, 13, -45, 5, -4, -2, 22, 18, 2, -19, 3, -20, -6, 4, -28, 21, 13, 18, -39, -7, -2, 2, 20, 22, 3, -17, 5, -16, -12, -10, -7, 13, 9, 8, -25, -19, 7, 6, 19, 25, 2, -15, 8, -12, -8, -3, -8, 15, 9, 15, -24, -29, 12, 2, 18, 28, 11, -4, -16, 4, -13, 3, -14, 19, 3, 15, -26, -25, 15, 4, 26, 17, 14, -13, -6, 4, -3, 2, -24, 21, -18, 26, -24, -8, 15, -8, 13, 12, 7, -7, -1, -5, -10, -2, -22, 15, 0, 24, -17, -2, 15, -17, 20, 12, 20, -10, 2, 10, -11, -11, -29, -22, -12, 7, -16, 7, 11, 0, 27, 9, 14, -14, -3, 10, -23, 16, -14, 7, -25, 18, -6, -9, 6, -31, 11, -6, 3, -9, -3, 17, 7, 0, -9, 1, -16, -5, -17, -6, -3, -101, 36, -3, 9, -2, -3, -13, 3, 5, -14, -5, -23, 6, -13, -1, -7, 1, 18, 6, 4, -11, -1, -25, -4, 12, 2, -16, 11, 4, -7, 2, -8, -1, -8, 8, -12, -2, -9, -38, -31, 12, 
  -1, -2, -8, 7, -33, 20, 6, -45, 26, 13, 0, 8, -10, -41, 5, -1, 18, 6, 5, 7, -12, 11, 2, -34, -12, 8, -10, 27, -27, -19, 7, -11, 20, 9, 1, 14, -12, 22, 1, -31, -9, -2, -20, 24, -8, -31, 5, 2, 25, 12, -9, 5, -13, 15, -1, -42, -2, -3, -13, 20, -7, -17, 11, -7, 16, 7, 7, 12, 5, 8, -7, -17, -11, -1, -10, 16, -28, -20, 9, -49, 8, 13, -8, -1, 17, 28, -2, -7, -37, 3, -6, 25, 13, -24, 19, -18, 5, 4, -4, 2, -13, 11, 1, -28, -30, 5, -18, 16, 6, -34, 12, -28, 2, 9, 21, -8, -22, 14, -6, -24, -26, 2, -1, 24, -4, -21, 18, 3, 13, 15, 15, -2, 5, 16, 5, -30, -9, 11, -4, 31, -2, -26, 21, 3, 18, 1, 9, -6, 4, 9, 0, -19, -8, 13, -7, 24, -23, -2, 11, -19, 18, 13, 16, 6, -13, 9, 7, 0, 12, 19, 3, 20, -44, -7, 8, 4, 19, 18, 12, 11, 0, 5, 6, -1, 6, 31, 1, 14, -34, -15, 6, 2, 4, -4, 0, -28, -70, 13, 11, 12, 9, 7, 13, 23, -27, 5, 13, 3, 
  -16, 10, -24, 18, -37, -12, 15, -7, 13, -18, -35, -27, 9, -74, 15, -34, -24, 11, -21, -6, -50, -6, 11, 8, 10, -1, -34, 4, 17, -67, 15, -29, -24, 11, -7, -11, -37, 6, 14, -1, 9, -14, -23, 12, 14, -29, 15, -42, -10, 8, -17, -20, -31, -17, 15, 8, 8, 6, -40, 10, 20, 0, 20, -32, 15, 3, -15, -26, -22, -54, 21, 6, 15, 6, -39, 13, 17, 8, 9, -35, 6, 6, -14, -30, -11, -41, 14, 15, 14, -1, -25, 11, -4, 19, 21, -40, 3, -3, -19, -18, -23, -24, 10, 10, 6, -10, -19, 8, 23, 8, 6, -61, 12, 6, -43, 11, -22, -17, -4, 13, 21, 6, -26, 5, 18, 11, -15, -53, 13, -25, -35, -10, -15, 9, -17, 22, 17, -24, -7, -3, 28, 13, -16, -53, 8, -8, -63, 0, 9, 7, -25, -1, -50, 13, -17, -5, 14, 9, -39, -43, -31, -11, -15, 9, -12, 10, -70, -50, -24, 1, -32, -14, 9, 6, -19, -32, -22, -2, -8, 0, -48, 10, -44, -17, -32, -25, -43, -8, 6, 13, -15, -15, 9, -40, -72, -27, -89, -4, 5, -10, 18, 10, 14, -46, 6, 13, -20, 9, 
  2, 2, 2, -9, -30, 20, -7, 2, 13, 7, -43, 6, -12, -37, 9, 0, -6, 5, 1, 10, -19, 3, 1, -2, 14, 2, -23, 3, 21, -28, 9, 7, -7, 10, 5, 1, -32, 9, 3, 0, 16, 4, -9, -9, 26, -28, 10, 8, -11, 7, 4, -2, -9, 7, -6, 11, 9, -12, -10, -13, 16, -42, 17, 1, 12, 2, 11, -11, -15, 7, 4, 13, 12, -7, 4, -15, 9, -55, 11, 15, -23, 1, 6, -1, -33, 9, 5, 17, 16, -25, -1, -29, 15, -38, 23, 11, -14, 2, 9, -13, -21, 3, -10, 9, 1, -29, 4, -26, 8, -40, 9, 4, -6, 8, 26, -13, -21, 10, -2, 6, 4, -10, 3, -16, 9, -33, 15, 24, -4, 11, 23, -17, -29, 5, 23, 11, 1, -14, 11, 0, -15, -34, 17, 57, -2, 1, 7, -21, -23, 7, 4, 28, 27, -15, 15, 1, -1, -25, 16, 35, 7, 18, 11, -2, -9, 9, 0, 15, 9, -23, 9, 3, 7, -2, 9, 19, 11, -1, 13, 11, -9, 12, 1, 7, 3, -4, 3, 4, 17, -21, -6, 20, -9, 57, 12, -11, -43, 16, -67, 12, 3, -24, -15, 1, 12, -10, -3, -10, 
  1, 1, -9, 11, 19, 11, -7, -8, -5, -10, -27, -12, 33, -7, -13, -17, 1, -1, 9, 8, 8, 4, -11, 1, -8, -7, -30, 5, 24, -15, -9, -5, 14, -3, 17, 11, 11, -14, -11, 8, -15, -6, -37, -9, 31, 6, -15, -5, 19, -3, 11, -2, 20, -23, -21, 15, -29, -30, -40, -8, 31, 3, -14, 3, 15, -5, 12, -22, 14, -27, -28, 24, -31, -19, -45, 3, 45, 3, -14, 9, 11, -20, 14, -10, 21, -30, -25, 19, -41, -32, -29, -8, 18, 7, -4, -3, 8, -8, 14, -9, 20, -13, -19, 15, -45, -30, -13, 0, 24, -1, -5, 5, 11, -16, -15, -5, 22, 15, -19, 15, -35, -29, -21, 6, 24, 0, 1, -6, 16, 7, -27, 14, -1, -3, -18, 0, -37, 4, -33, -3, 17, 6, -22, -26, -7, -7, -38, 6, -14, 7, 3, -19, -13, 1, -18, 7, 10, 0, -15, -3, -24, -7, -60, 12, -6, -4, 5, -71, -29, -8, -26, -2, 2, 6, -16, -19, -30, 3, -19, 20, -24, 2, 14, -86, -5, 23, -20, 0, 9, -11, -7, -22, 8, 3, -26, 29, 7, 7, 29, -127, 22, 17, 32, -8, 3, -10, -25, -49, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 8,208 } };
const TfArray<1, float> quant7_scale = { 1, { 0.017438815906643867, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[16] = { -2234, -2574, -2799, -232, -1006, -454, -8498, -2537, -814, -1143, 93, -1380, 1055, -1396, -811, -3392, };
const TfArray<1, int> tensor_dimension8 = { 1, { 16 } };
const TfArray<16, float> quant8_scale = { 16, { 0.0003359656548127532, 0.00030649054679088295, 0.00029612451908178627, 0.00040290821925736964, 0.00047991672181524336, 0.00035663860035128891, 0.00014898111112415791, 0.00036511683720164001, 0.00048806835548020899, 0.00027892045909538865, 0.00063590542413294315, 0.00027462502475827932, 0.00069647969212383032, 0.00027644523652270436, 0.00030395432258956134, 0.00028394421678967774, } };
const TfArray<16, int> quant8_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[16*1*3*8] = { 
  /* [0][0][][] */ 21,1,118,8,-6,7,4,-19, -2,-3,4,-9,-66,3,-11,-57, 2,-11,14,-19,-127,7,-76,-84, 
  /* [1][0][][] */ 3,17,-18,-44,-90,-25,-20,15, 1,20,9,-22,-83,-35,-33,-2, 12,45,20,-10,127,-31,-6,-9, 
  /* [2][0][][] */ -43,58,-13,-127,6,-28,5,3, -58,1,7,-71,45,-12,-14,13, -109,0,-10,-6,44,5,77,14, 
  /* [3][0][][] */ 4,19,18,-123,-102,-37,-15,26, 4,-25,-24,-20,29,-61,-33,-14, -9,-46,-127,28,-2,-20,7,47, 
  /* [4][0][][] */ 15,-13,-5,-18,-73,-53,-127,-7, 22,-2,-25,-28,-38,-34,-51,-27, -17,-20,-50,-12,-4,66,-18,-31, 
  /* [5][0][][] */ -40,47,-28,-19,-43,-17,-13,59, -71,-5,-47,-127,-6,-1,-12,-15, -63,40,-33,-45,-7,11,-4,-24, 
  /* [6][0][][] */ 25,-36,81,54,43,-74,-27,84, 94,-105,17,-29,61,-27,-71,-4, -39,-127,-119,81,63,6,33,-1, 
  /* [7][0][][] */ -125,-10,-1,-20,10,33,76,10, -127,-44,8,-29,25,-1,-21,13, -41,-59,9,-29,-5,11,31,-11, 
  /* [8][0][][] */ -24,-18,-94,29,41,-18,28,-2, -105,-61,-82,7,-29,-6,22,-20, -73,-123,-26,31,-127,8,3,-84, 
  /* [9][0][][] */ 8,-38,-108,122,-38,-1,-26,-23, -88,1,-3,-44,-36,1,-32,-109, -127,60,40,2,-88,7,-24,-122, 
  /* [10][0][][] */ -127,-6,-11,17,-5,7,-4,16, -124,-5,-16,3,-21,2,-5,-17, -61,-2,-24,13,-34,1,-10,45, 
  /* [11][0][][] */ 10,54,-2,32,-9,-26,-57,-13, -6,-7,127,21,-19,-28,-60,-1, -30,21,-48,-58,3,-26,-12,5, 
  /* [12][0][][] */ -3,1,-63,0,-32,-23,-109,-1, -3,0,-114,-2,-31,-15,-127,-10, -1,5,-62,15,-4,-19,-66,7, 
  /* [13][0][][] */ -64,-38,-1,-19,-106,108,-29,-2, 28,9,-9,-29,-127,-29,-45,17, 4,-1,-8,-67,-50,-22,-50,20, 
  /* [14][0][][] */ 24,-10,-26,-3,54,-16,-54,-127, -10,2,25,3,25,-29,-40,-81, 16,34,45,-15,74,-37,-31,-60, 
  /* [15][0][][] */ -7,-23,8,22,-10,-103,17,71, -1,-46,-12,8,-42,-127,63,-4, 26,-39,-63,19,-48,-71,3,14, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 16,1,3,8 } };
const TfArray<16, float> quant9_scale = { 16, { 0.0075937039218842983, 0.0069274897687137127, 0.0066931899636983871, 0.0091067813336849213, 0.010847375728189945, 0.0080609666183590889, 0.0033673634752631187, 0.008252597413957119, 0.011031623929738998, 0.0063043329864740372, 0.014373128302395344, 0.0062072449363768101, 0.015742266550660133, 0.0062483865767717361, 0.0068701640702784061, 0.0064178835600614548, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[8] = { -821, -2241, -1265, -3191, -4477, -5605, -6036, -4580, };
const TfArray<8, float> quant10_scale = { 8, { 0.00032207570620812476, 0.00030306715052574873, 0.00060050463071092963, 0.00034470210084691644, 0.00036668719258159399, 0.00019592266471590847, 0.00024641089839860797, 0.00021122739417478442, } };
const TfArray<8, int> quant10_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[8*1*3*13] = { 
  /* [0][0][][] */ 47,-32,-31,47,1,7,2,6,5,-29,-7,-14,-7, -115,-127,-12,6,22,-58,-36,-31,13,-1,23,47,-16, 26,-103,22,-3,37,34,-9,1,-4,3,-52,-15,36, 
  /* [1][0][][] */ -77,36,-9,31,33,52,3,15,-4,-57,-3,-8,-5, -96,127,69,-25,-42,21,18,13,-1,6,-57,59,17, -51,40,28,-9,-59,-9,-40,-20,1,-11,8,-3,-22, 
  /* [2][0][][] */ 127,38,3,23,-15,20,-11,5,-6,2,-2,10,1, -16,36,57,-9,4,-5,20,1,6,5,-11,-5,0, -102,-48,-15,-18,-22,-1,-20,-6,-4,-5,1,-10,3, 
  /* [3][0][][] */ 127,-46,-37,-16,32,-76,-48,46,39,-4,-39,7,41, 10,-48,-33,26,7,15,-21,50,8,-6,-4,-19,-4, 41,8,-36,32,60,19,9,-30,2,27,-7,-23,0, 
  /* [4][0][][] */ 30,-79,44,-56,-3,25,30,-23,6,15,-25,21,2, 127,-29,55,43,-5,25,-71,2,-10,6,-12,-10,15, 98,47,-19,37,-20,-15,-33,22,19,39,-5,23,-11, 
  /* [5][0][][] */ -7,-4,-83,-69,-19,53,85,-12,-28,27,13,20,3, 79,118,-93,-2,-3,85,52,-15,13,-9,-60,25,22, 105,75,4,-9,35,127,-2,21,49,-7,-16,-17,-45, 
  /* [6][0][][] */ 127,83,2,68,-74,5,-64,-6,3,12,-24,27,-19, 32,62,46,6,-2,-34,-10,-24,17,-43,45,-82,35, 115,63,-25,7,24,-80,65,-17,34,-42,59,-66,23, 
  /* [7][0][][] */ 110,15,40,14,97,54,-99,-20,-35,-5,-16,17,-30, -19,67,63,122,50,6,-41,51,-5,-51,14,36,-26, 34,127,9,98,68,5,50,22,37,-49,-21,18,17, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 8,1,3,13 } };
const TfArray<8, float> quant11_scale = { 8, { 0.006411183625459671, 0.0060328026302158833, 0.01195354200899601, 0.0068615810014307499, 0.0072992127388715744, 0.003900002921000123, 0.0049050133675336838, 0.0042046564631164074, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,49,13 } };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,1,49,8 } };
const TfArray<1, float> quant13_scale = { 1, { 0.044242657721042633, } };
const TfArray<1, int> quant13_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&quant13_zero, 0 };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,49,1,8 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,25,1,8 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,25,8 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,25,16 } };
const TfArray<1, float> quant17_scale = { 1, { 0.036131400614976883, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant13_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,25,1,16 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,13,1,16 } };
const TfArray<2, int> tensor_dimension20 = { 2, { 1,208 } };
const TfArray<2, int> tensor_dimension21 = { 2, { 1,8 } };
const TfArray<1, float> quant21_scale = { 1, { 0.13437329232692719, } };
const TfArray<1, int> quant21_zero = { 1, { 42 } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&quant21_zero, 0 };
const TfArray<1, float> quant22_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant22 = { (TfLiteFloatArray*)&quant22_scale, (TfLiteIntArray*)&g0::quant13_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 12 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 12,11,10 } };
const TfArray<1, int> outputs1 = { 1, { 13 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 13,2 } };
const TfArray<1, int> outputs2 = { 1, { 14 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 14 } };
const TfArray<1, int> outputs3 = { 1, { 15 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 15,3 } };
const TfArray<1, int> outputs4 = { 1, { 16 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 16,9,8 } };
const TfArray<1, int> outputs5 = { 1, { 17 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 17,4 } };
const TfArray<1, int> outputs6 = { 1, { 18 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 18 } };
const TfArray<1, int> outputs7 = { 1, { 19 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 19,5 } };
const TfArray<1, int> outputs8 = { 1, { 20 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 20,7,6 } };
const TfArray<1, int> outputs9 = { 1, { 21 } };
const TfLiteSoftmaxParams opdata10 = { 1 };
const TfArray<1, int> inputs10 = { 1, { 21 } };
const TfArray<1, int> outputs10 = { 1, { 22 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 640), (TfLiteIntArray*)&g0::tensor_dimension0, 637, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 1664, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension6, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 312, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 637, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 640), (TfLiteIntArray*)&g0::tensor_dimension13, 392, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 392, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension15, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension17, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension19, 208, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 208, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 208), (TfLiteIntArray*)&g0::tensor_dimension21, 8, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 8, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 23, };
const size_t tflNodes_subgraph_index[] = {0, 11, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  22, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1053353_5_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 23;
  for (size_t i = 0; i < 23; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1053353_5_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1053353_5_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1053353_5_invoke() {
  for (size_t i = 0; i < 11; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1053353_5_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
